//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gemo_test_application
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnalyzesForOrder
    {
        public int id { get; set; }
        public Nullable<int> id_Order { get; set; }
        public Nullable<int> id_Analyze { get; set; }
        public Nullable<bool> Needed { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Analyzes Analyzes { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
